### ISSUE TITLE
[Request] Will it be possible to share BEGIN-Adversarial silver training set from Section 4.2 of the paper?

### ISSUE THREAD

**Issue by abaheti95** [google/BEGIN-dataset#1]
Hi,
Thank you for sharing the dataset! Can you also share the training set for the BEGIN-Adversarial classifier?

**Comment by davidswelt** [comment]
Hi, thanks for your request. At this point we have no plans to share that training set, unfortunately.

**Comment by davidswelt** [comment]
(And consider ANLI as an adversarial dataset.)
